//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_38416
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ведомость.
    /// </summary>
    // *** Start programmer edit section *** (Ведомость CustomAttributes)

    // *** End programmer edit section *** (Ведомость CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВедомостьE", new string[] {
            "Оценка as \'Оценка\'",
            "Студент as \'Студент\'",
            "Студент.ФИО as \'ФИО\'",
            "Преподаватель as \'Преподаватель\'",
            "Преподаватель.ФИО as \'ФИО\'",
            "Дисциплина as \'Дисциплина\'",
            "Дисциплина.Название as \'Название\'"})]
    [View("ВедомостьL", new string[] {
            "Оценка as \'Оценка\'",
            "Студент.ФИО as \'ФИО\'",
            "Преподаватель.ФИО as \'ФИО\'",
            "Дисциплина.Название as \'Название\'"})]
    public class Ведомость : ICSSoft.STORMNET.DataObject
    {
        
        private int fОценка;
        
        private IIS.Product_38416.Студент fСтудент;
        
        private IIS.Product_38416.Преподаватель fПреподаватель;
        
        private IIS.Product_38416.Дисциплина fДисциплина;
        
        // *** Start programmer edit section *** (Ведомость CustomMembers)

        // *** End programmer edit section *** (Ведомость CustomMembers)

        
        /// <summary>
        /// Оценка.
        /// </summary>
        // *** Start programmer edit section *** (Ведомость.Оценка CustomAttributes)

        // *** End programmer edit section *** (Ведомость.Оценка CustomAttributes)
        public virtual int Оценка
        {
            get
            {
                // *** Start programmer edit section *** (Ведомость.Оценка Get start)

                // *** End programmer edit section *** (Ведомость.Оценка Get start)
                int result = this.fОценка;
                // *** Start programmer edit section *** (Ведомость.Оценка Get end)

                // *** End programmer edit section *** (Ведомость.Оценка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ведомость.Оценка Set start)

                // *** End programmer edit section *** (Ведомость.Оценка Set start)
                this.fОценка = value;
                // *** Start programmer edit section *** (Ведомость.Оценка Set end)

                // *** End programmer edit section *** (Ведомость.Оценка Set end)
            }
        }
        
        /// <summary>
        /// Ведомость.
        /// </summary>
        // *** Start programmer edit section *** (Ведомость.Студент CustomAttributes)

        // *** End programmer edit section *** (Ведомость.Студент CustomAttributes)
        [PropertyStorage(new string[] {
                "Студент"})]
        [NotNull()]
        public virtual IIS.Product_38416.Студент Студент
        {
            get
            {
                // *** Start programmer edit section *** (Ведомость.Студент Get start)

                // *** End programmer edit section *** (Ведомость.Студент Get start)
                IIS.Product_38416.Студент result = this.fСтудент;
                // *** Start programmer edit section *** (Ведомость.Студент Get end)

                // *** End programmer edit section *** (Ведомость.Студент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ведомость.Студент Set start)

                // *** End programmer edit section *** (Ведомость.Студент Set start)
                this.fСтудент = value;
                // *** Start programmer edit section *** (Ведомость.Студент Set end)

                // *** End programmer edit section *** (Ведомость.Студент Set end)
            }
        }
        
        /// <summary>
        /// Ведомость.
        /// </summary>
        // *** Start programmer edit section *** (Ведомость.Преподаватель CustomAttributes)

        // *** End programmer edit section *** (Ведомость.Преподаватель CustomAttributes)
        [PropertyStorage(new string[] {
                "Преподаватель"})]
        [NotNull()]
        public virtual IIS.Product_38416.Преподаватель Преподаватель
        {
            get
            {
                // *** Start programmer edit section *** (Ведомость.Преподаватель Get start)

                // *** End programmer edit section *** (Ведомость.Преподаватель Get start)
                IIS.Product_38416.Преподаватель result = this.fПреподаватель;
                // *** Start programmer edit section *** (Ведомость.Преподаватель Get end)

                // *** End programmer edit section *** (Ведомость.Преподаватель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ведомость.Преподаватель Set start)

                // *** End programmer edit section *** (Ведомость.Преподаватель Set start)
                this.fПреподаватель = value;
                // *** Start programmer edit section *** (Ведомость.Преподаватель Set end)

                // *** End programmer edit section *** (Ведомость.Преподаватель Set end)
            }
        }
        
        /// <summary>
        /// Ведомость.
        /// </summary>
        // *** Start programmer edit section *** (Ведомость.Дисциплина CustomAttributes)

        // *** End programmer edit section *** (Ведомость.Дисциплина CustomAttributes)
        [PropertyStorage(new string[] {
                "Дисциплина"})]
        [NotNull()]
        public virtual IIS.Product_38416.Дисциплина Дисциплина
        {
            get
            {
                // *** Start programmer edit section *** (Ведомость.Дисциплина Get start)

                // *** End programmer edit section *** (Ведомость.Дисциплина Get start)
                IIS.Product_38416.Дисциплина result = this.fДисциплина;
                // *** Start programmer edit section *** (Ведомость.Дисциплина Get end)

                // *** End programmer edit section *** (Ведомость.Дисциплина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ведомость.Дисциплина Set start)

                // *** End programmer edit section *** (Ведомость.Дисциплина Set start)
                this.fДисциплина = value;
                // *** Start programmer edit section *** (Ведомость.Дисциплина Set end)

                // *** End programmer edit section *** (Ведомость.Дисциплина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВедомостьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВедомостьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВедомостьE", typeof(IIS.Product_38416.Ведомость));
                }
            }
            
            /// <summary>
            /// "ВедомостьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВедомостьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВедомостьL", typeof(IIS.Product_38416.Ведомость));
                }
            }
        }
    }
}
