//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_38416
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Группа.
    /// </summary>
    // *** Start programmer edit section *** (Группа CustomAttributes)

    // *** End programmer edit section *** (Группа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГруппаE", new string[] {
            "Название as \'Название\'",
            "Факультет as \'Факультет\'",
            "Факультет.Название as \'Название\'"})]
    [View("ГруппаL", new string[] {
            "Название as \'Название\'",
            "Факультет.Название as \'Название\'"})]
    public class Группа : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private IIS.Product_38416.Факультет fФакультет;
        
        // *** Start programmer edit section *** (Группа CustomMembers)

        // *** End programmer edit section *** (Группа CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Группа.Название CustomAttributes)

        // *** End programmer edit section *** (Группа.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Группа.Название Get start)

                // *** End programmer edit section *** (Группа.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Группа.Название Get end)

                // *** End programmer edit section *** (Группа.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Группа.Название Set start)

                // *** End programmer edit section *** (Группа.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Группа.Название Set end)

                // *** End programmer edit section *** (Группа.Название Set end)
            }
        }
        
        /// <summary>
        /// Группа.
        /// </summary>
        // *** Start programmer edit section *** (Группа.Факультет CustomAttributes)

        // *** End programmer edit section *** (Группа.Факультет CustomAttributes)
        [PropertyStorage(new string[] {
                "Факультет"})]
        [NotNull()]
        public virtual IIS.Product_38416.Факультет Факультет
        {
            get
            {
                // *** Start programmer edit section *** (Группа.Факультет Get start)

                // *** End programmer edit section *** (Группа.Факультет Get start)
                IIS.Product_38416.Факультет result = this.fФакультет;
                // *** Start programmer edit section *** (Группа.Факультет Get end)

                // *** End programmer edit section *** (Группа.Факультет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Группа.Факультет Set start)

                // *** End programmer edit section *** (Группа.Факультет Set start)
                this.fФакультет = value;
                // *** Start programmer edit section *** (Группа.Факультет Set end)

                // *** End programmer edit section *** (Группа.Факультет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГруппаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаE", typeof(IIS.Product_38416.Группа));
                }
            }
            
            /// <summary>
            /// "ГруппаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаL", typeof(IIS.Product_38416.Группа));
                }
            }
        }
    }
}
