//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_38416
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Дисциплина.
    /// </summary>
    // *** Start programmer edit section *** (Дисциплина CustomAttributes)

    // *** End programmer edit section *** (Дисциплина CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДисциплинаE", new string[] {
            "Название as \'Название\'",
            "КоличествоСиместровИзучения as \'Количество симестров изучения\'"})]
    [View("ДисциплинаL", new string[] {
            "Название as \'Название\'",
            "КоличествоСиместровИзучения as \'Количество симестров изучения\'"})]
    public class Дисциплина : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private int fКоличествоСиместровИзучения;
        
        // *** Start programmer edit section *** (Дисциплина CustomMembers)

        // *** End programmer edit section *** (Дисциплина CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Дисциплина.Название CustomAttributes)

        // *** End programmer edit section *** (Дисциплина.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Дисциплина.Название Get start)

                // *** End programmer edit section *** (Дисциплина.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Дисциплина.Название Get end)

                // *** End programmer edit section *** (Дисциплина.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Дисциплина.Название Set start)

                // *** End programmer edit section *** (Дисциплина.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Дисциплина.Название Set end)

                // *** End programmer edit section *** (Дисциплина.Название Set end)
            }
        }
        
        /// <summary>
        /// КоличествоСиместровИзучения.
        /// </summary>
        // *** Start programmer edit section *** (Дисциплина.КоличествоСиместровИзучения CustomAttributes)

        // *** End programmer edit section *** (Дисциплина.КоличествоСиместровИзучения CustomAttributes)
        public virtual int КоличествоСиместровИзучения
        {
            get
            {
                // *** Start programmer edit section *** (Дисциплина.КоличествоСиместровИзучения Get start)

                // *** End programmer edit section *** (Дисциплина.КоличествоСиместровИзучения Get start)
                int result = this.fКоличествоСиместровИзучения;
                // *** Start programmer edit section *** (Дисциплина.КоличествоСиместровИзучения Get end)

                // *** End programmer edit section *** (Дисциплина.КоличествоСиместровИзучения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Дисциплина.КоличествоСиместровИзучения Set start)

                // *** End programmer edit section *** (Дисциплина.КоличествоСиместровИзучения Set start)
                this.fКоличествоСиместровИзучения = value;
                // *** Start programmer edit section *** (Дисциплина.КоличествоСиместровИзучения Set end)

                // *** End programmer edit section *** (Дисциплина.КоличествоСиместровИзучения Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДисциплинаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДисциплинаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДисциплинаE", typeof(IIS.Product_38416.Дисциплина));
                }
            }
            
            /// <summary>
            /// "ДисциплинаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДисциплинаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДисциплинаL", typeof(IIS.Product_38416.Дисциплина));
                }
            }
        }
    }
}
