//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_38416
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кафедра.
    /// </summary>
    // *** Start programmer edit section *** (Кафедра CustomAttributes)

    // *** End programmer edit section *** (Кафедра CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КафедраE", new string[] {
            "Название as \'Название\'"})]
    [View("КафедраL", new string[] {
            "Название as \'Название\'"})]
    public class Кафедра : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Кафедра CustomMembers)

        // *** End programmer edit section *** (Кафедра CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Кафедра.Название CustomAttributes)

        // *** End programmer edit section *** (Кафедра.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Кафедра.Название Get start)

                // *** End programmer edit section *** (Кафедра.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Кафедра.Название Get end)

                // *** End programmer edit section *** (Кафедра.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Кафедра.Название Set start)

                // *** End programmer edit section *** (Кафедра.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Кафедра.Название Set end)

                // *** End programmer edit section *** (Кафедра.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КафедраE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КафедраE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КафедраE", typeof(IIS.Product_38416.Кафедра));
                }
            }
            
            /// <summary>
            /// "КафедраL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КафедраL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КафедраL", typeof(IIS.Product_38416.Кафедра));
                }
            }
        }
    }
}
