//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_38416
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Преподаватель.
    /// </summary>
    // *** Start programmer edit section *** (Преподаватель CustomAttributes)

    // *** End programmer edit section *** (Преподаватель CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПреподавательE", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "Стаж as \'Стаж\'",
            "Кафедра as \'Кафедра\'",
            "Кафедра.Название as \'Название\'"})]
    [View("ПреподавательL", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "Стаж as \'Стаж\'",
            "Кафедра.Название as \'Название\'"})]
    public class Преподаватель : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private System.DateTime fДатаРождения;
        
        private int fСтаж;
        
        private IIS.Product_38416.Кафедра fКафедра;
        
        // *** Start programmer edit section *** (Преподаватель CustomMembers)

        // *** End programmer edit section *** (Преподаватель CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Преподаватель.ФИО CustomAttributes)

        // *** End programmer edit section *** (Преподаватель.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Преподаватель.ФИО Get start)

                // *** End programmer edit section *** (Преподаватель.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Преподаватель.ФИО Get end)

                // *** End programmer edit section *** (Преподаватель.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Преподаватель.ФИО Set start)

                // *** End programmer edit section *** (Преподаватель.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Преподаватель.ФИО Set end)

                // *** End programmer edit section *** (Преподаватель.ФИО Set end)
            }
        }
        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Преподаватель.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Преподаватель.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Преподаватель.ДатаРождения Get start)

                // *** End programmer edit section *** (Преподаватель.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Преподаватель.ДатаРождения Get end)

                // *** End programmer edit section *** (Преподаватель.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Преподаватель.ДатаРождения Set start)

                // *** End programmer edit section *** (Преподаватель.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Преподаватель.ДатаРождения Set end)

                // *** End programmer edit section *** (Преподаватель.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// Стаж.
        /// </summary>
        // *** Start programmer edit section *** (Преподаватель.Стаж CustomAttributes)

        // *** End programmer edit section *** (Преподаватель.Стаж CustomAttributes)
        public virtual int Стаж
        {
            get
            {
                // *** Start programmer edit section *** (Преподаватель.Стаж Get start)

                // *** End programmer edit section *** (Преподаватель.Стаж Get start)
                int result = this.fСтаж;
                // *** Start programmer edit section *** (Преподаватель.Стаж Get end)

                // *** End programmer edit section *** (Преподаватель.Стаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Преподаватель.Стаж Set start)

                // *** End programmer edit section *** (Преподаватель.Стаж Set start)
                this.fСтаж = value;
                // *** Start programmer edit section *** (Преподаватель.Стаж Set end)

                // *** End programmer edit section *** (Преподаватель.Стаж Set end)
            }
        }
        
        /// <summary>
        /// Преподаватель.
        /// </summary>
        // *** Start programmer edit section *** (Преподаватель.Кафедра CustomAttributes)

        // *** End programmer edit section *** (Преподаватель.Кафедра CustomAttributes)
        [PropertyStorage(new string[] {
                "Кафедра"})]
        [NotNull()]
        public virtual IIS.Product_38416.Кафедра Кафедра
        {
            get
            {
                // *** Start programmer edit section *** (Преподаватель.Кафедра Get start)

                // *** End programmer edit section *** (Преподаватель.Кафедра Get start)
                IIS.Product_38416.Кафедра result = this.fКафедра;
                // *** Start programmer edit section *** (Преподаватель.Кафедра Get end)

                // *** End programmer edit section *** (Преподаватель.Кафедра Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Преподаватель.Кафедра Set start)

                // *** End programmer edit section *** (Преподаватель.Кафедра Set start)
                this.fКафедра = value;
                // *** Start programmer edit section *** (Преподаватель.Кафедра Set end)

                // *** End programmer edit section *** (Преподаватель.Кафедра Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПреподавательE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПреподавательE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПреподавательE", typeof(IIS.Product_38416.Преподаватель));
                }
            }
            
            /// <summary>
            /// "ПреподавательL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПреподавательL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПреподавательL", typeof(IIS.Product_38416.Преподаватель));
                }
            }
        }
    }
}
