//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_38416
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Студент.
    /// </summary>
    // *** Start programmer edit section *** (Студент CustomAttributes)

    // *** End programmer edit section *** (Студент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтудентE", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "Группа as \'Группа\'",
            "Группа.Название as \'Название\'"})]
    [View("СтудентL", new string[] {
            "ФИО as \'ФИО\'",
            "ДатаРождения as \'Дата рождения\'",
            "Группа.Название as \'Название\'"})]
    public class Студент : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИО;
        
        private System.DateTime fДатаРождения;
        
        private IIS.Product_38416.Группа fГруппа;
        
        // *** Start programmer edit section *** (Студент CustomMembers)

        // *** End programmer edit section *** (Студент CustomMembers)

        
        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Студент.ФИО CustomAttributes)

        // *** End programmer edit section *** (Студент.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (Студент.ФИО Get start)

                // *** End programmer edit section *** (Студент.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (Студент.ФИО Get end)

                // *** End programmer edit section *** (Студент.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.ФИО Set start)

                // *** End programmer edit section *** (Студент.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (Студент.ФИО Set end)

                // *** End programmer edit section *** (Студент.ФИО Set end)
            }
        }
        
        /// <summary>
        /// ДатаРождения.
        /// </summary>
        // *** Start programmer edit section *** (Студент.ДатаРождения CustomAttributes)

        // *** End programmer edit section *** (Студент.ДатаРождения CustomAttributes)
        public virtual System.DateTime ДатаРождения
        {
            get
            {
                // *** Start programmer edit section *** (Студент.ДатаРождения Get start)

                // *** End programmer edit section *** (Студент.ДатаРождения Get start)
                System.DateTime result = this.fДатаРождения;
                // *** Start programmer edit section *** (Студент.ДатаРождения Get end)

                // *** End programmer edit section *** (Студент.ДатаРождения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.ДатаРождения Set start)

                // *** End programmer edit section *** (Студент.ДатаРождения Set start)
                this.fДатаРождения = value;
                // *** Start programmer edit section *** (Студент.ДатаРождения Set end)

                // *** End programmer edit section *** (Студент.ДатаРождения Set end)
            }
        }
        
        /// <summary>
        /// Студент.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Группа CustomAttributes)

        // *** End programmer edit section *** (Студент.Группа CustomAttributes)
        [PropertyStorage(new string[] {
                "Группа"})]
        [NotNull()]
        public virtual IIS.Product_38416.Группа Группа
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Группа Get start)

                // *** End programmer edit section *** (Студент.Группа Get start)
                IIS.Product_38416.Группа result = this.fГруппа;
                // *** Start programmer edit section *** (Студент.Группа Get end)

                // *** End programmer edit section *** (Студент.Группа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Группа Set start)

                // *** End programmer edit section *** (Студент.Группа Set start)
                this.fГруппа = value;
                // *** Start programmer edit section *** (Студент.Группа Set end)

                // *** End programmer edit section *** (Студент.Группа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтудентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтудентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтудентE", typeof(IIS.Product_38416.Студент));
                }
            }
            
            /// <summary>
            /// "СтудентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтудентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтудентL", typeof(IIS.Product_38416.Студент));
                }
            }
        }
    }
}
