/*flexberryautogenerated="true"*/
namespace IIS.Product_38416
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ВедомостьL : BaseListForm<Ведомость>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ВедомостьL() : base(Ведомость.Views.ВедомостьL)
        {
            EditPage = ВедомостьE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Vedomost/VedomostL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
