/*flexberryautogenerated="true"*/
namespace IIS.Product_38416
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class КафедраL : BaseListForm<Кафедра>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public КафедраL() : base(Кафедра.Views.КафедраL)
        {
            EditPage = КафедраE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Kafedra/KafedraL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
